// navbar
export const HOME_PAGE = "HOME_PAGE";
export const SEARCH_PAGE = "SEARCH_PAGE";
export const ADD_PAGE = "ADD_PAGE";
export const POPULAR_PAGE = "POPULAR_PAGE";
export const PROFILE_PAGE = "PROFILE_PAGE";

// auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

// profileInfo
export const PROFILE_INFO_START = 'PROFILE_INFO_START';
export const PROFILE_INFO_SUCCESS = 'PROFILE_INFO_SUCCESS';
export const PROFILE_INFO_FAIL = 'PROFILE_INFO_FAIL';

// profileRecipes
export const PROFILE_RECIPES_START = 'PROFILE_RECIPES_START';
export const PROFILE_RECIPES_SUCCESS = 'PROFILE_RECIPES_SUCCESS';
export const PROFILE_RECIPES_FAIL = 'PROFILE_RECIPES_FAIL';

// homeRecipes
export const HOME_RECIPES_START = 'HOME_RECIPES_START';
export const HOME_RECIPES_SUCCESS = 'HOME_RECIPES_SUCCESS';
export const HOME_RECIPES_FAIL = 'HOME_RECIPES_FAIL';

// popularRecipes
export const POPULAR_RECIPES_START = 'POPULAR_RECIPES_START';
export const POPULAR_RECIPES_SUCCESS = 'POPULAR_RECIPES_SUCCESS';
export const POPULAR_RECIPES_FAIL = 'POPULAR_RECIPES_FAIL';

// searchRecipes
export const SEARCH_RECIPES_START = 'SEARCH_RECIPES_START';
export const SEARCH_RECIPES_SUCCESS = 'SEARCH_RECIPES_SUCCESS';
export const SEARCH_RECIPES_FAIL = 'SEARCH_RECIPES_FAIL';