# Generated by Django 3.0.8 on 2020-08-25 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ingredient_recipe_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
