# Generated by Django 3.0.8 on 2020-08-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200825_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_hours',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
