# Generated by Django 3.0.8 on 2020-08-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_time_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_hours',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_minutes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
