# Generated by Django 3.0.8 on 2020-08-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200828_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
