# Generated by Django 3.0.11 on 2020-12-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_user_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='link',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time_minutes',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
